apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sample-app
  labels:
    app.kubernetes.io/type: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: java-sample-app
      app.kubernetes.io/instance: java-sample-app
      app.kubernetes.io/component: service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: java-sample-app
        app.kubernetes.io/instance: java-sample-app
        app.kubernetes.io/component: service
    spec:
      containers:
        - name: java-sample-app
          image: 314945786589.dkr.ecr.us-east-2.amazonaws.com/java-auto-instrumentation-sample-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      