apiVersion: v1
kind: Service
metadata:
  name: java-auto-instrumentation-sample-service
  labels:
    app: java-auto-instrumentation-sample-app
    tier: backend
spec:
  #type: Cluster IP is a default service
  selector:
    app: java-auto-instrumentation-sample-app
  ports:
    - name: http
      port: 8080 # ClusterIp Service Port
      targetPort: 8080 # Container Port
  