apiVersion: v1
kind: Service
metadata:
  name: java-sample
  labels:
    app: java-sample-app
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: java-sample-app
    app.kubernetes.io/instance: java-sample-app
    app.kubernetes.io/component: service
  